# ~~~~~~~
# hugo 本身的配置
# ~~~~~~~
baseURL: "https://Bencao.github.io/Bencao/" # 主站的 URL,绑定的域名
title: GEWUTANZE BENCAO # 站点标题
copyright: "Copyright © 2025 GewuTanze. 格物致知,探赜索隐." # 网站的版权声明，通常显示在页脚
theme: PaperMod # 主题

enableInlineShortcodes: true # shortcode，类似于模板变量，可以在写 markdown 的时候便捷地插入，官方文档中有一个视频讲的很通俗
hasCJKLanguage: true # 是否有 CJK 的字符,自动检测是否包含中文日文韩文,如果文章中使用了很多中文引号的话可以开启
enableRobotsTXT: true # 允许生成 robots.txt
buildDrafts: false # 构建时是否包括草稿
buildFuture: false # 构建未来发布的内容
buildExpired: false # 构建过期的内容
enableEmoji: true # 允许 emoji
pygmentsUseClasses: true # 使用 CSS 类名实现代码高亮
defaultContentLanguage: zh # 顶部首先展示的语言界面
defaultContentLanguageInSubdir: true # 是否要在地址栏加上默认的语言代码 多语言 true默认语言放入子目录中(例如 /en/)即使是默认语言，false默认语言会在根目录(例如 /)


# ~~~~~~~~~
# 主题的配置(基本上是)
# ~~~~~~~~~

pagination:
   pagerSize: 10  # 新的写法  每页展示的文章数量，这个没找到文档，应该是主题自己设置的

 # 搜索
fuseOpts:
      iscasesensitive : false
      includescore : false
      includematches : false
      minmatchcharlength : 2
      shouldsort : true
      findallmatches : false
      limit : 15
      keys : ["title^3", "tags^2.5", "summary^2", "author^2", "categories^1.5", "content^1"]
      location : 0
      threshold : 0.3
      distance : 80
      ignorelocation : true


markup:
  goldmark:
    renderer:
      unsafe: true # 可以 unsafe，有些 html 标签和样式可能需要
  highlight:
    anchorLineNos: false # 不要给行号设置锚标
    codeFences: true # 代码围栏
    noClasses: false # TODO: 不知道干啥的，暂时没必要了解，不影响展示
    lineNos: true # 代码行
    lineNumbersInTable: false # 不要设置成 true，否则如果文章开头是代码的话，摘要会由一大堆数字(即代码行号)开头文章
    # 这里设置 style 没用，得自己加 css
    # style: "github-dark"
    # style: monokai