main:
        - identifier: home
          name: 首页
          url: zh/
          weight: 2 # 控制在页面上展示的前后顺序

        - identifier: archives
          name: 归档
          url: zh/archives/
          weight: 5

        - identifier: categories
          name: 分类
          url: zh/categories/
          weight: 10

        - identifier: tags
          name: 标签
          url: zh/tags/
          weight: 10

        - identifier: notes
          name: 笔记
          url: zh/note/   #可在content文件夹下添加 zh-cn文件夹
          weight: 15

        - identifier: search
          name: 搜索
          url: zh/search/
          weight: 20

        - identifier: about
          name: 关于
          url: zh/about/
          weight: 21